version: '3.8'

services:
  merchandise-service:
    build: .
    hostname: merchandise-service
  
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock-api
    
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing-service

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply-service
  
  redis:
    image: redis
    hostname: redis
